# Generated by Django 4.0 on 2022-03-11 03:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=70)),
                ('current_status', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('activate_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
