# Generated by Django 4.0 on 2022-03-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Node', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='current_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
